clear: *.class 
	rm *.class 

run: Runner.java GiftNode.java ServantThread.java 
	javac Runner.java 
	javac Runner 

single: SingleThreaded.java GiftNode.java 
	javac SingleThreaded.java 
	java SingleThreaded 

