clean: *.class 
	rm *.class 

run: Runner.java GiftNode.java ServantThread.java 
	javac Runner.java 
	java Runner 

single: SingleThreaded.java GiftNode.java 
	javac SingleThreaded.java 
	java SingleThreaded 

test: Test.java GiftNode.java GiftList.java 
	javac Test.java 
	java Test